### ISSUE TITLE
Select SVG elements 

### ISSUE THREAD

**Issue by brmscheiner** [valerybugakov/react-selectable-fast#16]
Is it possible to use this library to select SVG elements? I set up a SelectableGroup inside my SVG tag with the class "timeline-selectable-group." Inside I see that the library has created an empty div for the selectionbox, but on mouseDown the class of that div does not change. Here is a simplified version of the DOM:

`<svg height="300px" width="500px">
  <g class="timeline-selectable-group">
    <div></div>
    <some selectable circles>
  </g>
</svg>`

**Comment by valerybugakov** [comment]
@brmscheiner could you check if `mouseDown` method in `Selectable-group.js` is triggered? Also it may not work because `div` is created inside of SVG element. Maybe this docs will be helpful: https://developer.mozilla.org/en/docs/Web/SVG/Element/foreignObject

Also I would try to wrap SVG inside of `div` as `SelectableGroup` if it's possible in your context.

**Comment by brmscheiner** [comment]
> Also I would try to wrap SVG inside of div as SelectableGroup if it's possible in your context.
that did the trick! thank you
